### ISSUE TITLE
Feature Request: support for ARS fiat currency

### ISSUE THREAD

**Issue by rainbyte** [BananoCoin/natrium-android-wallet#18]
It seems natrium does not support [ARS (Argentine Peso)](https://www.coingecko.com/en/coins/nano/historical_data/ars) currency yet.
Having extra fiat currencies would be really useful.

I can provide a patch if given minimal instructions to accomplish it.

Thanks in advance!

**Comment by bbedward** [comment]
Yep, it's already supported by coingecko API so I can add this pretty easily

**Comment by bbedward** [comment]
Closing since this was added to the flutter version in https://github.com/AvengeMedia/natrium_wallet_flutter/commit/a265989cc9649c0a2f3c2b695a4a1c688cd218d1 and https://github.com/BananoCoin/natrium-wallet-server/commit/d8de818f690773679eec0b8f517f604514da2d2a

The flutter version will be replacing the android version in the near future.
