### ISSUE TITLE
first transaction stuck at pending

### ISSUE THREAD

**Issue by fallerOfFalls** [BananoCoin/natrium-android-wallet#9]
I had no problem when I imported a seed, but this time I generated a new seed with the app, and it shows me a sort of "example transactions" page.

The first transaction went through. It's definitely been received by that address, and it even gave me a push notification. But the transactions interface only shows that "example transactions" page, and says I have zero nano.

Force stop does nothing. Restarting the phone does nothing. I'm assuming that if I reinstalled the app it would fix it, because then when I imported that seed it wouldn't show me that example transactions page because there is already one transaction. Uh, okay, that didn't work either. I'm just eternally stuck with example transactions.

I tried with a different seed that has many transactions, and it worked fine. So what's wrong with this one?

Ah, it's actually still pending. Okay. So it has failed to initialise.

**Comment by fallerOfFalls** [comment]
I'm guessing this is a node issue, nothing to do with the wallet. However, as a user it was very confusing because the push notification came through.

It would be great if the wallet had a way to see pending transactions?

**Comment by bbedward** [comment]
Hi, 

> It would be great if the wallet had a way to see pending transactions?

Agree, i've thought of some ways to display them

---

As far as the actual issue, it was a bug I forgot to account for pow on an open block in the last update. 

Was fixed in https://github.com/BananoCoin/natrium-wallet-server/commit/6c2e6964aec910abb629ed1ba09bd091e134e474

And is now deployed, since it's server change you don't need to wait for an app update or anything.

**Comment by fallerOfFalls** [comment]
Wooo thanks!
